config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :friends
  devise_for :users
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/chats",to: 'chats#index',as: :chat_index
  get "/chats/:username",to: 'chats#show',as: :show_chat
  post "/messages/upload_attachment",to: 'messages#upload_attachment',as: :upload_attachment
  get "/friends/add/(:user_id)",to: 'friends#add',as: :add_friend
  get "/friends/approve/(:user_id)",to: 'friends#approve',as: :approve_friend
  get "/documents/users/profile_pic/:user_id",to: 'chats#profile_pic',as: :profile_pic
  get "/chats/attachment/:message_id",to: 'chats#show_attachment',as: :show_attachment
  root controller: :chats, action: :index
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :friend
  mount_uploader :file_name, MediaUploader

  def partner_id
    friend = Friend.find(self.friend_id)
    return (friend.user_1_id==self.user_id)? friend.user_2_id : friend.user_1_id
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  after_action :broadcast_data, only: [:create,:upload_attachment]
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @friend = Friend.find(@message.friend_id)
    @message.user_id = current_user.id
    if !@message.message.nil?
     @message.sentiment = Aylien.check(@message.message)
    end
    respond_to do |format|
      if @message.save
        @hide_user_id = @friend.partner_id(current_user.id)
        format.json { render :show, status: :created, location: @message }
        format.js {render :'messages/create'}
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
        format.js {}
      end
    end

  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      endrender :'messages/create'
    end
    end
    end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upload_attachment
    @message = Message.new(file_name: params[:file])
    @friend = Friend.find(params[:friend_id].to_i)
    @message.friend_id = @friend.id
    @message.is_attachment = true
    @message.user_id = current_user.id
    if @message.save!
      @hide_user_id = @friend.partner_id(current_user.id)
      @message.update(:attachment_content_type=>@message.file_name.content_type)
      respond_to do |format|
        format.html {redirect_to "/chats/shubham"}
        format.json{ render :json => @message }
        format.js {render :'messages/upload_attachment'}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:friend_id, :message)
    end

   def broadcast_data
     messages = Message.where(:friend_id=>@friend.id,:read=>false,:user_id=>@message.partner_id)
     messages.update(:read=>true)
     FriendChannel.broadcast_to @friend, @message
     user = (@friend.user_1_id==current_user.id)? User.find(@friend.user_2_id) : User.find(@friend.user_1_id)
     AppearanceChannel.broadcast_to user,{user_id: current_user.id,notification_count: Message.where(:friend_id=>@friend.id,:read=>false,:user_id=>current_user.id).count}
   end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :friend_id %>
    <%= form.text_field :friend_id %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/create.js.erb
$('.emoji-wysiwyg-editor').html('');
$('#notification_<%= @hide_user_id%>').text("");

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Friend</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.friend %></td>
        <td><%= message.message %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Friend:</strong>
  <%= @message.friend %>
</p>

<p>
  <strong>Message:</strong>
  <%= @message.message %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/messages/upload_attachment.js.erb
alert();