config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :friends
  devise_for :users
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/chats",to: 'chats#index',as: :chat_index
  get "/chats/:username",to: 'chats#show',as: :show_chat
  post "/messages/upload_attachment",to: 'messages#upload_attachment',as: :upload_attachment
  get "/friends/add/(:user_id)",to: 'friends#add',as: :add_friend
  get "/friends/approve/(:user_id)",to: 'friends#approve',as: :approve_friend
  get "/documents/users/profile_pic/:user_id",to: 'chats#profile_pic',as: :profile_pic
  get "/chats/attachment/:message_id",to: 'chats#show_attachment',as: :show_attachment
  root controller: :chats, action: :index
end

app/models/friend.rb
class Friend < ApplicationRecord

  ## method to find whether searched username is friend of current logged in user or not.
  def self.find_friend_user_id(current_user,user_id)
    friends = Friend.where("user_1_id=? or user_2_id=?",current_user,current_user)
    @friends_user_id = []
    friends.pluck(:user_1_id,:user_2_id).each do |friend|
      (friend[0]==current_user)? @friends_user_id << friend[1] : @friends_user_id << friend[0]
    end
    if @friends_user_id.include?(user_id)
      return friends[@friends_user_id.index(user_id)].id
    end
    return nil
  end


  def partner_id(user_id)
   return (self.user_1_id==user_id)? self.user_2_id : self.user_1_id
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  # GET /friends
  # GET /friends.json
  def index
    @users = User.where.not(:id=>current_user)

  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add
    if Friend.find_friend_user_id(current_user.id,params[:user_id].to_i).nil?
      Friend.create(:user_1_id=>current_user.id,:user_2_id=>params[:user_id].to_i)
      flash[:notice]="Friend Request has been sent."
    else
      flash[:alert]="Friend Request has already been raised."
    end
    redirect_to "/friends"
  end

  def approve
    friend = Friend.find_friend_user_id(current_user.id,params[:user_id].to_i)
    if !friend.nil?
      Friend.find(friend).update(:approved=>true)
      flash[:notice]="You are friends now.."
    else
      flash[:alert]="Error."
    end
    redirect_to "/friends"
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_params
      params.require(:friend).permit(:user_1_id, :user_2_id, :block)
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% friend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_1_id %>
    <%= form.text_field :user_1_id %>
  </div>

  <div class="field">
    <%= form.label :user_2_id %>
    <%= form.text_field :user_2_id %>
  </div>

  <div class="field">
    <%= form.label :block %>
    <%= form.check_box :block %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Add new Friend</h1>

<table id="data_table" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Username</th>
      <th>Name</th>
      <th>Bio</th>
      <th></th>

    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <% if !user.avtar.url.nil? %>
            <img class="avatar" src="<%= user.avtar %>">
          <% else %>
            <img src="https://ptetutorials.com/images/user-profile.png" class="avatar" alt="">
          <% end %>
          </td>
        <td><%= user.username %></td>
        <td><%= user.full_name %></td>

        <td><%= user.bio%></td>
        <%friend = Friend.find_friend_user_id(current_user.id,user.id)%>

        <td>
          <%if friend.nil? %>
          <%= link_to 'Add Friend', add_friend_path(:user_id=>user) %>
          <%else %>
            <% friend = Friend.find(friend) %>

            <%if !friend.approved and friend.user_1_id != current_user.id %>
              <%= link_to 'Approve Request', approve_friend_path(:user_id=>user) %>
            <%elsif friend.approved%>
              <p>You are friends</p>
            <%else %>
              <p>Friend request has been sent.</p>
              <%end %>
          <%end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>



<script>
    $('#data_table').DataTable();
</script>
<%#= link_to 'New Friend', new_friend_path %>

app/views/friends/new.html.erb
<h1>New Friend</h1>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User 1:</strong>
  <%= @friend.user_1 %>
</p>

<p>
  <strong>User 2:</strong>
  <%= @friend.user_2 %>
</p>

<p>
  <strong>Block:</strong>
  <%= @friend.block %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>