config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :friends
  devise_for :users
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/chats",to: 'chats#index',as: :chat_index
  get "/chats/:username",to: 'chats#show',as: :show_chat
  post "/messages/upload_attachment",to: 'messages#upload_attachment',as: :upload_attachment
  get "/friends/add/(:user_id)",to: 'friends#add',as: :add_friend
  get "/friends/approve/(:user_id)",to: 'friends#approve',as: :approve_friend
  get "/documents/users/profile_pic/:user_id",to: 'chats#profile_pic',as: :profile_pic
  get "/chats/attachment/:message_id",to: 'chats#show_attachment',as: :show_attachment
  root controller: :chats, action: :index
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :show_friends,:except => [:profile_pic,:show_attachment]
  before_action :online_friends,:only=>[:index,:show]
  self.layout "chat"
  def index
  end

  def chat_box
    @username = params[:username]
  end

  def show
    @message = Message.new
    user_id = User.find_by(username: params[:username])
    @user = user_id
    if user_id
      @friend_id = Friend.find_friend_user_id(current_user.id,user_id.id)
      if Friend.find(@friend_id).approved
        @messages = Message.where(:friend_id => @friend_id)
      else
        flash[:alert] = "Currently you are not friend of #{params[:username]}."
        redirect_to chat_index_path
      end
    else
      flash[:alert]="User doesn't exsists"
      redirect_to chat_index_path
    end

  end

  def profile_pic
     user = User.find(params[:user_id])
     if !user.avtar.path.nil?
       file_path = current_user.avtar.path
       send_file(file_path,:disposition=>"inline")
     else
        send_file("#{Rails.root}/public/user-profile.png",:disposition=>"inline")
     end
  end

  def show_attachment
    message = Message.find(params[:message_id])
    if message
      friend = Friend.find(message.friend_id)
      if (friend.user_1_id==current_user.id or friend.user_2_id==current_user.id) and message.is_attachment
        send_file(message.file_name.path,:disposition=>"inline")
      else
        send_file("#{Rails.root}/public/danger.png",:disposition=>"inline")
      end
    else
      send_file("#{Rails.root}/public/danger.png",:disposition=>"inline")
    end

  end
  private
  def show_friends
    friends = Friend.where("(user_1_id=? or user_2_id=?) and approved=1",current_user,current_user)
    @friends_user_id = []
    friends.pluck(:user_1_id,:user_2_id).each do |friend|
      (friend[0]==current_user.id)? @friends_user_id << friend[1] : @friends_user_id << friend[0]
    end
    @f_name_map = User.where(:id=>@friends_user_id).map{|x| [x.id,x.full_name]}.to_h
    @f_uname_map = User.where(:id=>@friends_user_id).map{|x| [x.id,x.username]}.to_h
    @notifications = Message.where(:friend_id => friends,:read=>false)
  end

  def online_friends
    @online_users = REDIS.zrange("online_users",0,REDIS.zcard("online_users")).collect{|x| x.to_i}
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_friends.erb
<div class="mb-3">
  <%= link_to new_room_path, class: 'btn btn-primary' do %>
    Create a room
  <% end %>
</div>

<% if @rooms.present? %>
  <nav class="nav flex-column">
    <% @rooms.each do |room| %>
      <%= link_to room.name, room_path(room), class: 'nav-link room-nav-link' %>
    <% end %>
  </nav>
<% else %>
  <div class="text-muted">
    The are no rooms
  </div>
<% end %>

app/views/chats/_friends.html.erb
  <div class="col-12 col-md-3">
    <div class="mb-3">
      <%= link_to "/friends", class: "btn btn-primary" do %>
        Add a new Friend
      <% end %>
    </div>

   <div>
     <ul class="list-group">

     <% if @friends_user_id.present? %>

         <% @friends_user_id.each do |friend| %>
           <a href="<%= show_chat_path(username: @f_uname_map[friend])%>" class="online_users_link" style="text-decoration: none;color: black">

           <li class="list-group-item d-flex justify-content-between align-items-center">
             <div class="col-auto text-center">
               <% user = User.find(friend) %>
               <%if !user.avtar.url.nil? %>
                 <img class="avatar" src="<%= user.avtar%>">
               <% else %>
                 <img src="https://ptetutorials.com/images/user-profile.png" class="avatar" alt="">
                 <% end %>

             </div>
             <%= @f_name_map[friend] %>
             <% notification_count = @notifications.select{|x| x.user_id==friend}.count %>
             <span class="badge badge-primary" id="notification_<%= friend %>"><%= (notification_count!=0)? notification_count : ""%></span>
             <span class="badge badge-<%= (@online_users.include?(friend))? "success" :"light" %>" id="status_<%= friend %>"><%= (@online_users.include?(friend))? "Online" :"Offline" %></span>

           </li>
           </a>
         <% end %>

     <% else %>
       <div class="text-muted">
         You don't have any friends. Click on "Add a new Friend" and start a chat.
       </div>
     <% end %>
     </ul>
   </div>

</div>

app/views/chats/chat_box.html.erb
<h1><%= @username %></h1>

app/views/chats/index.html.erb
<div class="row">

  <%= render partial: 'friends' %>

  <div class="col">
    <div class="alert alert-primary">
      <h4 class="alert-heading">
        Welcome to the WebChatApp!
      </h4>
    </div>
  </div>
</div>

app/views/chats/show.html.erb
<input name="current_user" type="hidden" value="<%= current_user.id %>" id="current_user"/>
<div class="row">

    <%= render partial: 'friends' %>

    <%map = {1=>"👍",2=>"😊",3=>"😡"} %>
    <div class="col">
      <div class="header_box">
       <br>
        <h1 class="text-center">
          <%= @user.full_name %>
        </h1>
      </div>

      <div class="box">
        <div class="chat" data-channel-subscribe="friend" data-friend-id="<%= @friend_id %>">
          <% @messages.each do |message| %>
            <div class="chat-message-container">
              <div class="row no-gutters">
                <div class="col">
                      <%if message.is_attachment and message.file_name.content_type.include?("image")%>
                        <div >
                        <%= image_tag message.file_name.url,class: (message.user_id == current_user.id) ? "message-content_img1" : "message-content_img"%>

                        <%elsif message.is_attachment %>
                          <div>
                            <a href="<%= message.file_name.url%>" target="_blank">
                            <%= image_tag "/download-logo.png",class: (message.user_id == current_user.id) ? "message-content_img1" : "message-content_img"%></a>
                        <%else %>
                         <div class="<%= (message.user_id == current_user.id) ? "message-content1" : "message-content" %>">
                          <p class="mb-1">
                            <%= message.message %>
                          </p>
                           <div class="text-right">
                             <span data-role="sentiment"> <%=map[message.sentiment]%></span> | <small><i data-role="message-date"><%= message.created_at.localtime.to_formatted_s(:short)%></i></small>


                           </div>
                        <%end %>

                  </div>
                </div>
              </div>
            </div>

          <% end %>

        </div>
        <%= form_for @message, remote: true do |form| %>
          <div class="input-group mb-3" style="width:495px">
            <div class="input-group-append">
            <p class="emoji-picker-container" style="width: 82vh">
              <%= form.text_field :message,
                                  input_html: {
                                      class: 'chat-input'
                                  }, data: {emojiable: true} %>


            </p>
              &nbsp;&nbsp;
              <%= form.submit "Send", class: 'btn btn-primary btn-xs chat-input' %>
              &nbsp;&nbsp;
              <button type="button" class="btn  btn-lg" data-toggle="modal" data-target="#myModal">
                <img src="/attachment_logo.png" style="height: 50px;width:30px"></button>
            </div>
          </div>

          <%= form.hidden_field :friend_id, :value => @friend_id %>
        <% end %>
      </div>


    </div>



  </div>
<div class="d-none" data-role="message-template">
  <div class="chat-message-container">
    <div class="row no-gutters">
      <div class="col">
        <div class="message-content" data-role="message-content">
          <p class="mb-1" data-role="message-text"></p>

          <div class="text-right">
            <span data-role="sentiment"> </span> | <small><i data-role="message-date"></i></small>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
  <div class="d-none" data-role="image-template">
    <div class="chat-message-container">
      <div class="row no-gutters">

        <div class="col">
          <div data-role="image_attachment_container">
            <img data-role="image" class="message-content_img" src="">
        </div>
          <div data-role="other_attachment_container">
            <a data-role="other" href="" target="_blank">
              <%= image_tag "/download-logo.png","data-role":  "other_img", class: "message-content_img" %></a>
          </div>

        </div>
    </div>
  </div>
  </div>
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-body">
        <div id="attachment">
          <form action="/messages/upload_attachment" id="media-dropzone" class="dropzone" enctype="multipart/form-data">
            <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>
            <input name="friend_id" type="hidden" value="<%= @friend_id %>"/>
            <div class="fallback">

              <input name="media" type="file" multiple/>

            </div>
          </form>
        </div>
      </div>
    </div>

  </div>
</div>

  <script>

  </script>